app/models/account.py
from datetime import datetime
from . import db

class Accounts(db.Model):
    """Accounts model"""
    __tablename__ = 'accounts'

    id = db.Column(db.Integer, nullable=False, primary_key=True)
    name = db.Column(db.Text)
    account_type = db.Column(db.Text)
    balance = db.Column(db.Numeric(10,2))
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.now)

    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    transactions = db.relationship('Transactions', backref='account', lazy=True, cascade="all, delete-orphan")

app/models/budget.py
from datetime import datetime
from . import db

class Budgets(db.Model):
    """Budgets model"""
    __tablename__ = 'budgets'

    id = db.Column(db.Integer, primary_key=True)
    category_name = db.Column(db.Text, nullable=False)
    amount = db.Column(db.Numeric(10,2), nullable=False)

    spent = db.Column(db.Numeric(10,2), nullable=True)
    start_date = db.Column(db.Date)
    end_date = db.Column(db.Date)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.now)

    category_id = db.Column(db.Integer, db.ForeignKey('categories.id'), nullable=False)
    category = db.relationship('Category', backref='budgets')
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)

    def __repr__(self):
        return f"<Budget id={self.id}, category_name={self.category_name}, amount={self.amount}, start_date={self.start_date}, end_date={self.end_date}, created_at={self.created_at}>"

app/routes/account.py
from flask import Blueprint, render_template, redirect, url_for, session, flash
from forms import AccountCreationForm
from app.models import db
from app.models.account import Accounts
from app.utils.charts import create_account_balance_chart

account_bp = Blueprint('account', __name__)

@account_bp.route('/add', methods=["GET", "POST"])
def add_account():
    if 'user_id' not in session:
        flash("You must be logged in to add an account.", "warning")
        return redirect(url_for('auth.login'))
    
    form = AccountCreationForm()
    if form.validate_on_submit():
        new_account = Accounts(
            name=form.name.data,
            account_type=form.account_type.data,
            balance=form.balance.data,
            user_id=session['user_id']
        )
        db.session.add(new_account)
        try:
            db.session.commit()
            flash("Account added successfully.", "success")
            return redirect(url_for('account.accounts'))
        except Exception as e:
            db.session.rollback()
            flash("Error adding account. Please try again.", "danger")
    return render_template('forms-templates/add-account.html', form=form)

@account_bp.route('/')
def accounts():
    if 'user_id' not in session:
        flash("You must be logged in to view accounts.", "warning")
        return redirect(url_for('auth.login'))
    
    user_id = session['user_id']
    balance_chart_div = create_account_balance_chart(user_id)
    user_accounts = Accounts.query.filter_by(user_id=user_id).all()

    return render_template('mainpages/accounts.html', accounts=user_accounts, balance_chart_div=balance_chart_div)


@account_bp.route('/edit/<int:account_id>', methods=["GET", "POST"])
def edit_account(account_id):
    if 'user_id' not in session:
        flash("You must be logged in to perform this action", "danger")
        return redirect(url_for('auth.login'))
    
    account_to_edit = Accounts.query.get_or_404(account_id)
    if account_to_edit.user_id != session['user_id']:
        flash("You don't have permission to edit this account", "danger")
        return redirect(url_for('account.accounts'))
    
    form = AccountCreationForm(obj=account_to_edit)

    if form.validate_on_submit():
        account_to_edit.name = form.name.data
        account_to_edit.account_type = form.account_type.data
        account_to_edit.balance = form.balance.data
        db.session.commit()
        flash("Account updated successfully.", "success")
        return redirect(url_for('account.accounts'))
    
    return render_template('forms-templates/edit-account.html', form=form, account=account_to_edit)

@account_bp.route('/delete/<int:account_id>', methods=['POST'])
def delete_account(account_id):
    if 'user_id' not in session:
        flash("You must be logged in to perform this action.", "warning")
        return redirect(url_for('auth.login'))
    
    account_to_delete = Accounts.query.get_or_404(account_id)
    if account_to_delete.user_id != session['user_id']:
        flash("You do not have permission to delete this account.", "danger")
        return redirect(url_for('account.accounts'))

    db.session.delete(account_to_delete)
    db.session.commit()
    flash("Account and related transactions deleted successfully.", "success")
    return redirect(url_for('account.accounts'))

app/routes/budget.py
from flask import Blueprint, render_template, redirect, url_for, session, flash
from forms import BudgetCreationForm
from app.models import db
from app.models.budget import Budgets
from app.models.category import Category
from app.utils.charts import create_budget_vs_spent_chart

budget_bp = Blueprint('budget', __name__)

@budget_bp.route('/set', methods=["GET", "POST"])
def set_budget():
    if 'user_id' not in session:
        flash("You must be logged in to set a budget.", "warning")
        return redirect(url_for('auth.login'))
    
    form = BudgetCreationForm()
    form.category.choices = [(str(c.id), c.name) for c in Category.query.order_by('name').all()]

    if form.validate_on_submit():
        category_id = int(form.category.data)
        category = Category.query.get(category_id)

        if category is None:
            flash(f"Category with ID '{category_id}' does not exist.", "danger")
            return redirect(url_for('budget.set_budget'))

        new_budget = Budgets(
            category_name=category.name,
            amount=form.amount.data,
            start_date=form.start_date.data,
            end_date=form.end_date.data,
            user_id=session['user_id'],
            category_id=category_id 
        )

        db.session.add(new_budget)
        try:
            db.session.commit()
            flash("Budget added.", "success")
            return redirect(url_for('budget.budgets'))
        except Exception as e:
            db.session.rollback()
            flash("Error setting budget.", "danger")
    return render_template('forms-templates/set-budget.html', form=form)

@budget_bp.route('/')
def budgets():
    if 'user_id' not in session:
        flash("You must be logged in to view accounts.", "warning")
        return redirect(url_for('auth.login'))
    
    user_id = session['user_id']
    budgets = Budgets.query.filter_by(user_id=user_id).all()

    budget_chart_div = create_budget_vs_spent_chart(session['user_id'])
    return render_template('mainpages/budgets.html', budget_chart_div=budget_chart_div, budgets=budgets)

@budget_bp.route('/delete/<int:budget_id>', methods=["POST"])
def delete_budget(budget_id):
    if 'user_id' not in session:
        flash("You must be logged in to perform this action.", "warning")
        return redirect(url_for('login'))
    
    budget_to_delete = Budgets.query.get_or_404(budget_id)
    if budget_to_delete.user_id != session['user_id']:
        return redirect(url_for('budgets'))
    db.session.delete(budget_to_delete)
    db.session.commit()
    flash("budget deleted successfully.", "success")
    return redirect(url_for('budget.budgets'))



@budget_bp.route('/edit/<int:budget_id>', methods=["GET", "POST"])
def edit_budget(budget_id):
    if 'user_id' not in session:
        flash("You must be logged in to perform this action", "danger")
        return redirect(url_for('login'))
    
    budget_to_edit = Budgets.query.get_or_404(budget_id)
    if budget_to_edit.user_id != session['user_id']:
        flash("You don't have permission to edit this budget.", "danger")
        return redirect(url_for('budget.budgets'))
    
    form = BudgetCreationForm(obj=budget_to_edit)

    form.category.choices = [(category.id, category.name) for category in Category.query.all()]

    if form.validate_on_submit():
        budget_to_edit.category_id = form.category.data
        budget_to_edit.amount = form.amount.data
        budget_to_edit.start_date = form.start_date.data
        budget_to_edit.end_date = form.end_date.data
        db.session.commit()
        return redirect(url_for('budget.budgets'))
    
    return render_template('forms-templates/edit-budget.html', form=form, budget=budget_to_edit)

app/routes/goal.py
from flask import Blueprint, render_template, redirect, url_for, session, flash
from forms import GoalCreationForm
from app.models import db
from app.models.goal import Goals

goal_bp = Blueprint('goal', __name__)

@goal_bp.route('/set', methods=["GET", "POST"])
def set_goal():
    if 'user_id' not in session:
        flash("You must be logged in to set a budget.", "warning")
        return redirect(url_for('auth.login'))
    
    form = GoalCreationForm()
    if form.validate_on_submit():
        new_goal = Goals(
            name=form.name.data,
            target_amount=form.target_amount.data,
            user_id=session['user_id']
        )
        db.session.add(new_goal)

        try:
            db.session.commit()
            flash("Goal added.", "success")
            return redirect(url_for('goal.goals'))
        except Exception as e:
            db.session.rollback()
            flash("Error setting goal.", "danger")
    return render_template('forms-templates/set-goal.html', form=form)

@goal_bp.route('/')
def goals():
    if 'user_id' not in session:
        flash("You must be logged in to view accounts.", "warning")
        return redirect(url_for('auth.login'))
    user_id = session['user_id']
    user_goals = Goals.query.filter_by(user_id=user_id).all()

    return render_template('mainpages/goals.html', goals=user_goals)

@goal_bp.route('/edit/<int:goal_id>', methods=["GET", "POST"])
def edit_goal(goal_id):
    if 'user_id' not in session:
        flash("You must be logged in to perform this action.", "warning")
        return redirect(url_for('login'))
    
    goal_to_edit = Goals.query.get_or_404(goal_id)
    if goal_to_edit.user_id != session['user_id']:
        flash("You do not have permission to edit this goal.", "danger")
        return redirect(url_for('goal.goals'))
    
    form = GoalCreationForm(obj=goal_to_edit)

    if form.validate_on_submit():
        goal_to_edit.name = form.name.data
        goal_to_edit.target_amount = form.target_amount.data
        db.session.commit()
        flash("Goal updated successfully.", "success")
        return redirect(url_for('goal.goals'))
    
    return render_template('forms-templates/edit-goal.html', form=form, goal=goal_to_edit)

@goal_bp.route('/delete/<int:goal_id>', methods=["POST"])
def delete_goal(goal_id):
    if 'user_id' not in session:
        flash("You must be logged in to perform this action.", "warning")
        return redirect(url_for('login'))
    
    goal_to_delete = Goals.query.get_or_404(goal_id)
    if goal_to_delete.user_id != session['user_id']:
        flash("You do not have permission to delete this account.", "danger")
        return redirect(url_for('goals'))
    db.session.delete(goal_to_delete)
    db.session.commit()
    flash("Goal deleted successfully.", "success")
    return redirect(url_for('goal.goals'))

app/routes/transaction.py
from flask import Blueprint, render_template, redirect, url_for, session, flash
from forms import TransactionForm
from app.models import db
from app.models.transaction import Transactions
from app.models.account import Accounts
from app.models.category import Category
from app.models.budget import Budgets
from decimal import Decimal

transaction_bp = Blueprint('transaction', __name__)

@transaction_bp.route('/add', methods=['GET', 'POST'])
def add_transaction():
    if 'user_id' not in session:
        flash("You must be logged in to add a transaction.", "warning")
        return redirect(url_for('auth.login'))

    form = TransactionForm()
    form.account_id.choices = [(str(account.id), account.name) for account in Accounts.query.filter_by(user_id=session['user_id']).all()]
    form.category.choices = [(str(category.id), category.name) for category in Category.query.all()]

    if form.validate_on_submit():
        transaction_type = form.type.data
        category_id = int(form.category.data) if transaction_type == 'expense' else None
        account = Accounts.query.get(int(form.account_id.data))

        if not account:
            flash("Account not found.", "danger")
            return render_template('forms-templates/add-transaction.html', form=form)

        transaction_amount = Decimal(form.amount.data)

        if transaction_type == 'income':
            account.balance += transaction_amount
        else:
            account.balance -= transaction_amount

        new_transaction = Transactions(
            type=transaction_type,
            description=form.description.data,
            amount=transaction_amount,
            date=form.date.data,
            account_id=account.id,
            user_id=session['user_id'],
            category_id=category_id
        )
        db.session.add(new_transaction)

        if transaction_type == 'expense':
            active_budget = Budgets.query.filter(
                Budgets.category_id == category_id,
                Budgets.start_date <= new_transaction.date,
                Budgets.end_date >= new_transaction.date,
                Budgets.user_id == session['user_id']
            ).first()

            if active_budget:
                if active_budget.spent is None:
                    active_budget.spent = Decimal('0')
                active_budget.spent += transaction_amount

        db.session.commit()
        flash('Transaction added successfully!', 'success')
        return redirect(url_for('transaction.transactions'))

    return render_template('forms-templates/add-transaction.html', form=form)

@transaction_bp.route('/')
def transactions():
    if 'user_id' not in session:
        flash("You must be logged in to view accounts.", "warning")
        return redirect(url_for('auth.login'))
    user_id = session['user_id']
    user_transactions = Transactions.query.filter_by(user_id=user_id).all()

    return render_template('mainpages/transactions.html', transactions=user_transactions)

@transaction_bp.route('/edit/<int:transaction_id>', methods=["GET", "POST"])
def edit_transaction(transaction_id):
    if 'user_id' not in session:
        flash("You must be logged in to perform this action.", "danger")
        return redirect(url_for('auth.login'))
    
    transaction_to_edit = Transactions.query.get_or_404(transaction_id)
    if transaction_to_edit.user_id != session['user_id']:
        flash("You don't have permission to edit this transaction.", "danger")
        return redirect(url_for('transaction.transactions'))
    
    form = TransactionForm(obj=transaction_to_edit)

    form.account_id.choices = [(account.id, account.name) for account in Accounts.query.all()]
    form.category.choices = [(category.id, category.name) for category in Category.query.all()]

    if form.validate_on_submit():
        old_amount = transaction_to_edit.amount
        old_type = transaction_to_edit.type
        old_account = Accounts.query.get(transaction_to_edit.account_id)

        new_amount = Decimal(form.amount.data)
        new_type = form.type.data
        new_account = Accounts.query.get(form.account_id.data)

        if old_type == 'income':
            old_account.balance -+ old_amount
        elif old_type == 'expense':
            old_account.balance += old_amount

        
        if new_type == 'income':
            new_account.balance += new_amount
        elif new_type == 'expense':
            new_account.balance -= new_amount

        transaction_to_edit.account_id = form.account_id.data
        transaction_to_edit.type = new_type
        transaction_to_edit.description = form.description.data
        transaction_to_edit.amount = form.amount.data
        transaction_to_edit.date = form.date.data
        transaction_to_edit.category_id = form.category.data if new_type == 'expense' else None
        db.session.commit()
        flash("Transaction updated successfully.", "success")
        return redirect(url_for('transaction.transactions'))

    return render_template('forms-templates/edit-transaction.html', form=form, transaction=transaction_to_edit)

@transaction_bp.route('/delete/<int:transaction_id>', methods=["POST"])
def delete_transaction(transaction_id):
    if 'user_id' not in session:
        flash("Yu must be logged in to perform this action.", "warning")
        return redirect(url_for('auth.login'))
    
    transaction_to_delete = Transactions.query.get_or_404(transaction_id)
    if transaction_to_delete.user_id != session['user_id']:
        return redirect(url_for('transaction.transactions'))
    
    account = Accounts.query.get(transaction_to_delete.account_id)

    if transaction_to_delete.type == 'income':
        account.balance -= transaction_to_delete.amount
    elif transaction_to_delete.type == 'expense':
        account.balance += transaction_to_delete.amount

    db.session.delete(transaction_to_delete)
    db.session.commit()
    flash("Transaction deleted successfully.", "success")
    return redirect(url_for('transaction.transactions'))

app/templates/mainpages/accounts.html
{% extends "base.html" %}

{% block title %}Your Accounts{% endblock %}

{% block content %}
<div class="container">
    <h2>Your Accounts</h2>
    
    <div id="balance-chart">{{ balance_chart_div|safe }}</div>
    <table class="table table-bg-color">
        <thead>
            <tr>
                <th>Account Name</th>
                <th>Account Type</th>
                <th>Balance</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for account in accounts %}
            <tr>
                <td>{{ account.name }}</td>
                <td>{{ account.account_type }}</td>
                <td>${{ account.balance }}</td>
                <td>
                    <a href="{{ url_for('account.edit_account', account_id=account.id) }}" class="btn btn-info">Edit</a>
                    <form action="{{ url_for('account.delete_account', account_id=account.id) }}" method="POST" onsubmit="return confirmDeletion()">
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div>
    <a href="{{ url_for('account.add_account') }}" class="btn btn-primary btn-lg btn-margin">Add New Account</a>
</div>
{% endblock %}

app/templates/mainpages/budgets.html
{% extends "base.html" %}

{% block title %}Your Budgets{% endblock %}

{% block content %}
<div class="container">
    <h2>Your Budgets</h2>
    <div id="budget-chart">
        {{ budget_chart_div|safe }}
      </div>

    <table class="table table-bg-color">
        <thead>
            <tr>
                <th>Category</th>
                <th>Amount</th>
                <th>Start Date</th>
                <th>End Date</th>
            </tr>
        </thead>
        <tbody>
            {% for budget in budgets %}
            <tr>
                <td>{{ budget.category.name }}</td>
                <td>${{ '%.2f'|format(budget.amount) }}</td>
                <td>{{ budget.start_date.strftime('%Y-%m-%d') }}</td>
                <td>{{ budget.end_date.strftime('%Y-%m-%d') }}</td>
                <td>
                    <a href="{{ url_for('budget.edit_budget', budget_id=budget.id) }}" class="btn btn-info">Edit</a>
                    <form action="{{ url_for('budget.delete_budget', budget_id=budget.id) }}" method="POST" onsubmit="return confirmDeletion()">
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div>
    <a href="{{ url_for('budget.set_budget') }}" class="btn btn-primary btn-lg btn-margin">Set New Budget</a>
</div>

{% endblock %}

app/templates/mainpages/goals.html
{% extends "base.html" %}

{% block title %}Your Goals{% endblock %}

{% block content %}
<div class="container">
    <h2>Your Goals</h2>
    
    <table class="table table-bg-color">
        <thead>
            <tr>
                <th>Name</th>
                <th>Target Amount</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for goal in goals %}
            <tr>
                <td>{{ goal.name }}</td>
                <td>${{ goal.target_amount }}</td>
                <td>
                    <a href="{{ url_for('goal.edit_goal', goal_id=goal.id) }}" class="btn btn-info">Edit</a>
                    <form action="{{ url_for('goal.delete_goal', goal_id=goal.id) }}" method="POST" onsubmit="return confirmDeletion()" style="display:inline-block;">
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div>
    <a href="{{ url_for('goal.set_goal') }}" class="btn btn-primary btn-lg btn-margin">Set New Goal</a>
</div>
{% endblock %}

app/templates/mainpages/transactions.html
{% extends "base.html" %}

{% block title %}Your Transactions{% endblock %}

{% block content %}
<div class="container">
    <h2>Your Transactions</h2>
    
    <table class="table table-bg-color">
        <thead>
            <tr>
                <th>Date</th>
                <th>Category</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            {% for transaction in transactions %}
            <tr>
                <td>{{ transaction.date }}</td>
                <td>{{ transaction.category.name }}</td>
                <td>${{ transaction.amount  }}</td>
                <td>
                    <a href="{{ url_for('transaction.edit_transaction', transaction_id=transaction.id) }}" class="btn btn-info">Edit</a>
                    <form action="{{ url_for('transaction.delete_transaction', transaction_id=transaction.id) }}" method="POST" onsubmit="return confirmDeletion()">
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div>
    <a href="{{ url_for('transaction.add_transaction') }}" class="btn btn-primary btn-lg btn-margin">Add New Transaction</a>
</div>
{% endblock %}