app/routes/auth.py
from flask import Blueprint, render_template, redirect, session, g, flash, url_for
from forms import UserLoginForm, RegistrationForm
from app.models.user import User
from app.models import db
from sqlalchemy.exc import IntegrityError
from app.utils.auth import do_login, do_logout
from flask_bcrypt import Bcrypt

auth_bp = Blueprint('auth', __name__)
bcrypt = Bcrypt()

@auth_bp.before_app_request
def add_user_to_g():
    if "user_id" in session:
        g.user = User.query.get(session["user_id"])
    else:
        g.user = None

@auth_bp.route('/signup', methods=['GET', 'POST'], endpoint='registration')
def signup():
    form = RegistrationForm()
    if form.validate_on_submit():
        try:
            existing_user = User.query.filter(
                (User.email == form.email.data) | (User.username == form.username.data)
            ).first()
            if existing_user:
                flash("Email or username already taken. Please choose another.", "danger")
                return render_template('signup.html', form=form)

            user = User.signup(
                first_name=form.first_name.data,
                last_name=form.last_name.data,
                username=form.username.data,
                email=form.email.data,
                password=form.password.data,
            )
            if user:
                do_login(user)
                flash("Welcome!", "success")
                return redirect(url_for('main.after_login'))
            else:
                flash("Signup failed. Please try again.", "danger")
                return render_template('signup.html', form=form)
        except IntegrityError as e:
            db.session.rollback()
            flash(f"An error occurred: {str(e)}", "danger")
            return render_template('signup.html', form=form)
    else:
        return render_template('signup.html', form=form)

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = UserLoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(form.password.data):
            session['user_id'] = user.id
            flash('You are logged in.', 'success')
            return redirect(url_for('main.after_login'))
        flash('Invalid email or password.', 'danger')
    return render_template('login.html', form=form)


@auth_bp.route('/logout', endpoint='logout')
def logout():
    do_logout()
    flash("You have successfully logged out.", "success")
    return redirect(url_for('main.home'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Welcome{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('main.after_login') }}">Wealth Watcher</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    {% if g.user %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.registration') }}">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container mt-4">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}">{{ message }}</div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        function confirmDeletion() {
            return confirm("Are you sure you want to delete?");
        }
    </script>
</body>
</html>

app/templates/homepage.html
{% extends "base.html" %}

{% block title %}Home Page{% endblock %}

{% block content %}
    <div class="text-center" style="margin-top: 50px;">
        <h1>Wealth Watcher</h1>
        <p>Manage your finances easily and efficiently.</p>
        <div>
            <a href="{{ url_for('auth.registration') }}" class="btn btn-primary">Sign Up</a>
            <a href="{{ url_for('auth.login') }}" class="btn btn-info">Login</a>
        </div>
    </div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container">
    <h2>Login</h2>
    <form method="POST" action="{{ url_for('auth.login') }}">
        {{ form.hidden_tag() }}
        
        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {{ form.email(class="form-control") }}
            {% for error in form.email.errors %}
                <small class="text-danger">{{ error }}</small>
            {% endfor %}
        </div>

        <div class="form-group">
            {{ form.password.label(class="form-control-label") }}
            {{ form.password(class="form-control") }}
            {% for error in form.password.errors %}
                <small class="text-danger">{{ error }}</small>
            {% endfor %}
        </div>

        <button type="submit" class="btn btn-primary">Login</button>
    </form>
</div>
{% endblock %}

app/templates/main-page.html
{% extends "base.html" %}

{% block title %}Main Page{% endblock %}

{% block content %}
    <div class="text-center" style="margin-top: 50px;">
        <h1>Wealth Watcher</h1>
        <p>Welcome, {{ g.user.first_name }}</p>
        <p>Manage your finances easily and efficiently.</p>
        <div id="accountsChart" class="plotly-graph-div">
          {{ accounts_plot_div|safe }}
      </div>
      <div id="financialsChart" class="plotly-graph-div">
        {{ financials_plot_div|safe }}
      </div>
        <div>
            <a href="{{ url_for('account.accounts') }}" class="btn btn-primary btn-lg btn-margin">Accounts</a>
            <a href="{{ url_for('transaction.transactions') }}" class="btn btn-primary btn-lg btn-margin">Transactions</a>
            <a href="{{ url_for('budget.budgets') }}" class="btn btn-primary btn-lg btn-margin">Budgets</a>
            <a href="{{ url_for('goal.goals') }}" class="btn btn-primary btn-lg btn-margin">Goals</a>
        </div>
    </div>
{% endblock %}

app/templates/signup.html
{% extends "base.html" %}

{% block title %}Signup{% endblock %}

{% block content %}
<div class="container">
    <h2>Signup</h2>
    <form method="POST" action="{{ url_for('auth.registration') }}">
        {{ form.hidden_tag() }}
        
        <div class="form-group">
            {{ form.first_name.label(class="form-control-label") }}
            {{ form.first_name(class="form-control") }}
            {% if form.first_name.errors %}
                {% for error in form.first_name.errors %}
                    <small class="text-danger">{{ error }}</small>
                {% endfor %}
            {% endif %}
        </div>
        
        <div class="form-group">
            {{ form.last_name.label(class="form-control-label") }}
            {{ form.last_name(class="form-control") }}
            {% if form.last_name.errors %}
                {% for error in form.last_name.errors %}
                    <small class="text-danger">{{ error }}</small>
                {% endfor %}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.username.label(class="form-control-label") }}
            {{ form.username(class="form-control") }}
            {% if form.username.errors %}
                {% for error in form.username.errors %}
                    <small class="text-danger">{{ error }}</small>
                {% endfor %}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {{ form.email(class="form-control") }}
            {% if form.email.errors %}
                {% for error in form.email.errors %}
                    <small class="text-danger">{{ error }}</small>
                {% endfor %}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.password.label(class="form-control-label") }}
            {{ form.password(class="form-control") }}
            {% if form.password.errors %}
                {% for error in form.password.errors %}
                    <small class="text-danger">{{ error }}</small>
                {% endfor %}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.confirm_password.label(class="form-control-label") }}
            {{ form.confirm_password(class="form-control") }}
            {% if form.confirm_password.errors %}
                {% for error in form.confirm_password.errors %}
                    <small class="text-danger">{{ error }}</small>
                {% endfor %}
            {% endif %}
        </div>

        <button type="submit" class="btn btn-primary">Signup</button>
    </form>
</div>
{% endblock %}